name: check_v1

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v2.2.0
        with:
          args: --no-progress --accept 200,429 --exclude "http://localhost(:[0-9]+)?/" --exclude "enode://*" --exclude "http://127.0.0.1(:[0-9]+)?/" --verbose "**/*.md" "**/*.mdx" "**/*.tsx" "**/*.rs" "**/*.ts"

  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Codespell
        run: pip install codespell

      - name: Run Codespell
        run: |
          codespell \
          --ignore-words=.codespellrc \
          --skip="*.min.js,*.json,*.lock,*.bin,*.svg"

  spellcheck_2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Spell Check with Typos
        uses: crate-ci/typos@v1.29.5
        with:
          files: |
            **/*
            !**/*.min.js
            !**/*.json
            !**/*.lock
            !**/*.bin
            !**/*.svg
          isolated: true

  spellcheck_yandex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests module
        run: pip install requests

      - name: Run Yandex.Speller
        run: |
          set -e
          find . -type f \( -name "*.md" -o -name "*.rs" -o -name "*.ts" -o -name "*.tsx" -o -name "*.mdx" \) > files.txt

          while IFS= read -r file; do
            echo "Checking $file"
            content=$(cat "$file" | tr '\n' ' ' | tr -s ' ' | head -c 10000)
            if [ -z "$content" ]; then continue; fi

            echo "$content" | python3 - "$file" <<EOF
import sys, requests
text = sys.stdin.read()
file = sys.argv[1]
url = 'https://speller.yandex.net/services/spellservice.json/checkText'
params = {'text': text, 'lang': 'en,ru'}
resp = requests.get(url, params=params)
errors = resp.json()
if errors:
    print(f'Found spelling issues in: {file}')
    for err in errors:
        word = err.get('word')
        suggestions = ', '.join(err.get('s', []))
        print(f"- Word: {word}, Suggestions: {suggestions}")
    sys.exit(1)
EOF
          done
